import React, { useState, useEffect, useRef } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import AISuggestions from '../components/AISuggestions';
import { mockTickets } from '../mockData';

const TicketDetail = () => {
    const { id } = useParams();
    const [ticket, setTicket] = useState(null);
    const [messages, setMessages] = useState([]);
    const [newMessage, setNewMessage] = useState('');
    const [suggestion, setSuggestion] = useState('');
    const [loadingSuggestion, setLoadingSuggestion] = useState(false);
    const [error, setError] = useState(null);
    const messagesEndRef = useRef(null);

    useEffect(() => {
        fetchTicketDetails();
    }, [id]);

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    const fetchTicketDetails = async () => {
        try {
            // Mock Data Implementation
            const foundTicket = mockTickets.find(t => t._id === id);
            if (foundTicket) {
                setTicket(foundTicket);
                setMessages(foundTicket.messages || []);
            } else {
                setError('Ticket not found');
            }
        } catch (err) {
            setError(err.message);
        }
    };

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    };

    const handleSendMessage = async (e) => {
        e.preventDefault();
        if (!newMessage.trim()) return;

        // Mock Sender Logic
        const newMsg = {
            _id: `msg_${Date.now()}`,
            content: newMessage,
            sender: 'agent',
            createdAt: new Date().toISOString()
        };
        setMessages([...messages, newMsg]);
        setNewMessage('');
        setSuggestion('');
    };

    const handleGenerateSuggestion = async () => {
        setLoadingSuggestion(true);
        // Mock AI Request
        setTimeout(() => {
            setSuggestion("This is a mock AI suggestion. In a real environment, this would be generated by OpenAI based on the ticket context.");
            setLoadingSuggestion(false);
        }, 1000);
    };

    const applySuggestion = (text) => {
        setNewMessage(text);
    };

    if (!ticket && error) {
        return (
            <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
                <p className="text-red-600 font-medium">⚠️ {error}</p>
                <button
                    onClick={() => window.location.href = '/tickets'}
                    className="mt-4 bg-primary hover:bg-indigo-700 text-white px-4 py-2 rounded-lg text-sm"
                >
                    Back to Tickets
                </button>
            </div>
        );
    }

    if (!ticket) return <div className="p-8">Loading...</div>;

    return (
        <div className="flex h-[calc(100vh-8rem)] gap-6">
            {/* Messages Area */}
            <div className="flex-1 flex flex-col bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
                    <div>
                        <h2 className="text-lg font-semibold text-gray-800">{ticket.title}</h2>
                        <div className="flex items-center text-xs text-gray-500 mt-1">
                            <span className="bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full mr-2">{ticket.category}</span>
                            <span>{ticket.customerEmail}</span>
                        </div>
                    </div>
                    <span className={`px-2 py-1 text-xs font-semibold rounded-full 
                ${ticket.status === 'Open' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                        {ticket.status}
                    </span>
                </div>

                <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-slate-50">
                    {messages.map((msg) => (
                        <div key={msg._id} className={`flex ${msg.sender === 'agent' ? 'justify-end' : 'justify-start'}`}>
                            <div className={`max-w-[80%] rounded-lg p-3 text-sm shadow-sm
                        ${msg.sender === 'agent'
                                    ? 'bg-primary text-white rounded-br-none'
                                    : msg.sender === 'ai'
                                        ? 'bg-purple-100 text-purple-900 border border-purple-200'
                                        : 'bg-white text-gray-800 border border-gray-200 rounded-bl-none'
                                }
                    `}>
                                {msg.sender === 'ai' && <div className="text-[10px] uppercase font-bold text-purple-600 mb-1">🤖 AI Assistant</div>}
                                <p>{msg.content}</p>
                                <span className={`block text-[10px] mt-1 opacity-70 ${msg.sender === 'agent' ? 'text-indigo-100' : 'text-gray-400'}`}>
                                    {new Date(msg.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                </span>
                            </div>
                        </div>
                    ))}
                    <div ref={messagesEndRef} />
                </div>

                <div className="p-4 bg-white border-t border-gray-100">
                    <AISuggestions
                        suggestion={suggestion}
                        loading={loadingSuggestion}
                        onGenerate={handleGenerateSuggestion}
                        onApply={applySuggestion}
                        onDismiss={() => setSuggestion('')}
                    />

                    <form onSubmit={handleSendMessage} className="flex gap-2">
                        <input
                            type="text"
                            value={newMessage}
                            onChange={(e) => setNewMessage(e.target.value)}
                            placeholder="Type your reply..."
                            className="flex-1 border border-gray-300 rounded-lg px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-shadow"
                        />
                        <button
                            type="submit"
                            className="bg-primary hover:bg-indigo-700 text-white px-6 py-2 rounded-lg text-sm font-medium transition-colors shadow-sm disabled:opacity-50"
                            disabled={!newMessage.trim()}
                        >
                            Send
                        </button>
                    </form>
                </div>
            </div>

            {/* Sidebar Info (Customer details, history, actions) */}
            <div className="w-80 bg-white rounded-xl shadow-sm border border-gray-100 p-6 hidden lg:block">
                <h3 className="font-semibold text-gray-800 mb-4">Customer Details</h3>
                <div className="space-y-4">
                    <div className="flex items-center">
                        <div className="h-10 w-10 rounded-full bg-gray-200 flex items-center justify-center text-gray-500 font-bold mr-3">
                            {ticket.customerName?.[0] || 'U'}
                        </div>
                        <div>
                            <div className="text-sm font-medium text-gray-900">{ticket.customerName || 'Unknown User'}</div>
                            <div className="text-xs text-gray-500">{ticket.customerEmail}</div>
                        </div>
                    </div>

                    <div className="pt-4 border-t border-gray-100">
                        <h4 className="text-xs font-semibold text-gray-500 uppercase mb-2">Ticket Info</h4>
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <span className="block text-xs text-gray-400">Created</span>
                                <span className="text-sm text-gray-800">{new Date(ticket.createdAt).toLocaleDateString()}</span>
                            </div>
                            <div>
                                <span className="block text-xs text-gray-400">Category</span>
                                <span className="text-sm text-gray-800">{ticket.category}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TicketDetail;
